"""unique id users

Revision ID: c15f08754904
Revises: 5ccaa0fac84e
Create Date: 2026-03-01 00:41:15.805619

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c15f08754904"
down_revision: str | Sequence[str] | None = "5ccaa0fac84e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f("uq_users_id"), "users", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_users_id"), "users", type_="unique")
    # ### end Alembic commands ###
